### ISSUE TITLE
Wimdows 11 x64 JRE

### ISSUE THREAD

**Issue by MDo94** [LightHouseGaming/Scrcpy-GUI#3]
I'm using Win11 21H2 x64 and it says that I need JRE 1.80 - 1.9.0.
I have installed in my machine JDK 17 from Adoptium.

![Screenshot (5)](https://user-images.githubusercontent.com/37194235/158271596-4d426e49-9279-4163-b13a-5fdef1d7c12a.png)

**Comment by LightHouseGaming** [comment]
https://www.java.com/en/download/manual.jsp

Update Coming This Week

But For Now, This Should Solve Your Current Issue, Will Push An Updated Version With New UI And Advanced Section For Those Looking To Record Or Use Exotic Scripts With It

**Comment by LightHouseGaming** [comment]
@MDo94 There Is a Minor Release Where Some Issues Of v1.0 Have Been Solved
